### ISSUE TITLE
Scroller utils not exported

### ISSUE THREAD

**Issue by gurkerl83** [code-hike/codehike#447]
Hi,
I noticed that the scroller utilities are currently not exported. We would like to use these utilities instead of the selection utilities because our existing components already manage the selection state through a custom player setup. The selection utilities are tied to a specific internal state, which overlaps with our existing setup, making them less suitable for our needs.

On the other hand, the scroller utilities are designed to be agnostic about the selection state, allowing them to be used independently without relying on the selection component. This flexibility makes them a better fit for our implementation.

Could you please export the scroller utilities in the same manner as the selection utilities in the package.json?

Thx!

**Comment by pomber** [comment]
Hi

I recommend copy-pasting the `scroller.tsx` to your project, since it isn't something directly related to Code Hike. In fact, all the things under `utils` were added to make the migration (from v0 to v1) and the examples easier to follow, it's totally fine to replace them with your own versions.

Does that work for you?
